import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";

const root = new URL("../", import.meta.url);
const out = new URL("../dist/", import.meta.url);
const data = JSON.parse(await readFile(new URL("../data/services.json", import.meta.url), "utf8"));
const money = (n) => new Intl.NumberFormat("ru-RU").format(n);

const safe = (value) => String(value).replace(/[&<>\"']/g, (c) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);
const title = (page = "Клининг и химчистка") => `${page} в Екатеринбурге — ${data.brand}`;
const head = ({ page, description, canonical, schema = [] }) => `<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#0b7774"><meta name="description" content="${safe(description)}">
<link rel="canonical" href="https://example.ru/${canonical}"><link rel="manifest" href="/site.webmanifest"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/site.css">
<meta property="og:type" content="website"><meta property="og:locale" content="ru_RU"><meta property="og:title" content="${safe(title(page))}"><meta property="og:description" content="${safe(description)}"><meta property="og:image" content="https://example.ru/assets/hero-interior.webp"><title>${safe(title(page))}</title>
${schema.map((item) => `<script type="application/ld+json">${JSON.stringify(item)}</script>`).join("\n")}</head>`;
const nav = () => `<header class="site-header"><a class="brand" href="/" aria-label="На главную"><span class="brand-mark">✦</span><span>${safe(data.brand)}</span></a><button class="nav-toggle" aria-label="Открыть меню" aria-expanded="false">Меню</button><nav><a href="/#services">Услуги</a><a href="/#calculator">Калькулятор</a><a href="/#booking">Запись</a><a href="/#faq">FAQ</a><a class="button button-small" href="/#calculator">Рассчитать</a></nav></header>`;
const footer = () => `<footer><div><a class="brand" href="/"><span class="brand-mark">✦</span><span>${safe(data.brand)}</span></a><p>Клининг и химчистка с выездом<br>по Екатеринбургу.</p></div><div><strong>Связаться</strong><a href="tel:${safe(data.phone.replace(/[^+\d]/g,""))}">${safe(data.phone)}</a><a href="${safe(data.telegram)}" target="_blank" rel="noopener">Telegram</a><a href="${safe(data.max)}" target="_blank" rel="noopener">MAX</a></div><div><strong>Документы</strong><a href="/privacy.html">Обработка персональных данных</a><a href="/sitemap.xml">Карта сайта</a><small>© ${new Date().getFullYear()} ${safe(data.brand)}. Самозанятая.</small></div></footer><div class="mobile-cta"><a href="tel:${safe(data.phone.replace(/[^+\d]/g,""))}">Позвонить</a><a href="/#calculator">Рассчитать стоимость</a></div><script src="/assets/config.js"></script><script src="/assets/site.js" defer></script></body></html>`;
const layout = (body, options) => `${head(options)}<body>${nav()}<main>${body}</main>${footer()}`;
const serviceSchema = (service) => ({"@context":"https://schema.org","@type":"Service",name:service.name,description:service.description,areaServed:data.city,provider:{"@type":"HouseCleaningService",name:data.brand},offers:{"@type":"Offer",price:service.price,priceCurrency:"RUB",availability:"https://schema.org/InStock"}});
const serviceCard = (s) => `<article class="service-card"><p class="eyebrow">${safe(s.duration)}</p><h3>${safe(s.name)}</h3><p>${safe(s.short)}</p><div class="price">от ${money(s.price)} ₽</div><a href="/${s.slug}.html" aria-label="Подробнее: ${safe(s.name)}">Подробнее <span>→</span></a></article>`;
const faq = [{q:"Сколько длится уборка?",a:"Обычно от 2 до 10 часов — это зависит от услуги, площади и степени загрязнения. Время уточним до выезда."},{q:"Нужны ли свои средства?",a:"Нет, специалист приезжает с необходимым инвентарём. Если у вас есть предпочтения по средствам или поверхностям, расскажите заранее."},{q:"Безопасно ли для детей и животных?",a:"Подберём подходящие средства и согласуем ограничения. На время работ и до высыхания поверхностей лучше обеспечить комфортную дистанцию."},{q:"Как подготовиться к озонированию?",a:"Следуйте инструкции мастера: из помещения выводят людей, животных и растения. После обработки необходимо проветривание. Озонирование не является медицинской услугой."},{q:"Как считается химчистка?",a:"Стартовая цена указана на сайте. Итог зависит от размера, материала, загрязнений и доступа к предмету — точную сумму можно подтвердить по фото."}];
const localBusinessSchema = {"@context":"https://schema.org","@type":"HouseCleaningService",name:data.brand,description:"Клининг и химчистка с выездом по Екатеринбургу",areaServed:{"@type":"City",name:data.city},openingHours:"Mo-Su 08:00-20:00",priceRange:"₽₽",hasOfferCatalog:{"@type":"OfferCatalog",name:"Услуги",itemListElement:data.services.map((s)=>({"@type":"Offer",itemOffered:{"@type":"Service",name:s.name},price:s.price,priceCurrency:"RUB"}))}};
const faqSchema = {"@context":"https://schema.org","@type":"FAQPage",mainEntity:faq.map((item)=>({"@type":"Question",name:item.q,acceptedAnswer:{"@type":"Answer",text:item.a}}))};

const home = () => layout(`<section class="hero"><div class="hero-copy"><p class="eyebrow light">Екатеринбург · ежедневно 8:00–20:00</p><h1>Чистота, в которой<br>легко <em>дышать</em>.</h1><p class="hero-lead">Клининг и химчистка с выездом по Екатеринбургу. Бережно к дому, внимательно к деталям.</p><div class="hero-actions"><a class="button" href="#calculator">Рассчитать стоимость <span>→</span></a><a class="button button-ghost" href="#photo">Отправить фото</a></div><div class="hero-proof"><span>✦ Самозанятая</span><span>✦ Цена до начала работ</span><span>✦ Выезд во все районы</span></div></div><div class="hero-image"><img src="/assets/hero-interior.webp" width="1536" height="1024" fetchpriority="high" alt="Светлая чистая гостиная с мягким диваном"></div><div class="floating-note">Пароочиститель<br><b>и бережные средства</b></div></section>
<section class="ticker" aria-label="Услуги"><div>${data.services.concat(data.services).map(s=>`<span>${safe(s.name)}</span><i>✦</i>`).join("")}</div></section>
<section class="section services" id="services"><div class="section-heading"><p class="eyebrow">Что сделаем</p><h2>Дом станет легче,<br><em>а не просто чище.</em></h2><p>Выберите задачу — заранее объясним объём работ и от чего зависит цена.</p></div><div class="service-grid">${data.services.map(serviceCard).join("")}</div></section>
<section class="section calculator-section" id="calculator"><div><p class="eyebrow">Быстрая оценка</p><h2>Сориентируем<br>по <em>стоимости.</em></h2><p>Это предварительный расчёт. Точную цену подтвердим после деталей или фото.</p></div><form class="calculator" novalidate><label>Что нужно сделать<select name="service">${data.services.map(s=>`<option value="${s.slug}" data-price="${s.price}">${safe(s.name)} — от ${money(s.price)} ₽</option>`).join("")}</select></label><div class="form-grid"><label>Площадь, м²<input name="area" type="number" min="1" value="40" inputmode="numeric"></label><label>Комнат<select name="rooms"><option value="1">1</option><option value="1.12" selected>2</option><option value="1.24">3</option><option value="1.38">4+</option></select></label></div><div class="checks"><label><input name="windows" type="checkbox"> Окна</label><label><input name="heavy" type="checkbox"> Сильные загрязнения</label><label><input name="urgent" type="checkbox"> Срочно</label></div><output aria-live="polite"><small>Предварительная стоимость</small><b>от <span>2 500</span> ₽</b></output><a class="button calculator-book" href="#booking">Выбрать время <span>→</span></a></form></section>
<section class="section booking-section" id="booking"><div class="booking-copy"><p class="eyebrow">Онлайн-запись</p><h2>Выберите удобное<br><em>время.</em></h2><p>Запись подтвердится только после ответа сервера. Если связь нестабильна, всегда можно позвонить или написать.</p><a class="text-link" href="tel:${safe(data.phone.replace(/[^+\d]/g,""))}">Позвонить ${safe(data.phone)} →</a></div><form id="booking-form" class="booking-form" novalidate><div class="form-grid"><label>Услуга<select name="service" required>${data.services.map(s=>`<option value="${s.slug}">${safe(s.name)}</option>`).join("")}</select></label><label>Дата<input type="date" name="date" required></label></div><label>Свободное время<select name="slot" required disabled><option>Сначала выберите дату</option></select></label><div class="form-grid"><label>Ваше имя<input name="name" autocomplete="name" minlength="2" required></label><label>Телефон<input name="phone" autocomplete="tel" inputmode="tel" placeholder="+7 900 000-00-00" required></label></div><label class="consent"><input name="consent" type="checkbox" required> <span>Согласен(-на) на <a href="/privacy.html" target="_blank">обработку персональных данных</a> для обратной связи и записи.</span></label><button class="button" type="submit">Отправить заявку <span>→</span></button><p class="form-status" aria-live="polite"></p></form></section>
<section class="section photo" id="photo"><div><p class="eyebrow">Оценка по фото</p><h2>Сомневаетесь в цене?<br><em>Покажите задачу.</em></h2><p>Отправьте фото дивана, ковра или помещения в мессенджер. Уточним стоимость до выезда — без догадок.</p></div><div class="photo-actions"><a class="messenger-card" href="${safe(data.telegram)}" target="_blank" rel="noopener"><b>Telegram</b><span>Отправить фото →</span></a><a class="messenger-card" href="${safe(data.max)}" target="_blank" rel="noopener"><b>MAX</b><span>Отправить фото →</span></a></div></section>
<section class="section trust"><p class="eyebrow">Спокойствие в деталях</p><h2>Забота, которую<br><em>видно сразу.</em></h2><div class="trust-grid"><article><span>01</span><h3>Бережные средства</h3><p>Подбираем подход к материалам, дому и вашим пожеланиям.</p></article><article><span>02</span><h3>Без сюрпризов</h3><p>Согласуем объём и стоимость до начала работ.</p></article><article><span>03</span><h3>Аккуратный выезд</h3><p>Приезжаем во все районы Екатеринбурга по записи.</p></article><article><span>04</span><h3>Напомним заранее</h3><p>Подтвердим визит, чтобы день прошёл спокойно.</p></article></div></section>
<section class="section cases"><div class="section-heading"><p class="eyebrow">Результат</p><h2>Настоящие кейсы<br><em>появятся здесь.</em></h2><p>Вместо выдуманных отзывов — реальные работы и согласованные истории клиентов.</p></div><div class="case-grid"><article><span>Ваш кейс</span><h3>Гостиная после<br>бережной химчистки</h3><p>Фото «до / после» публикуем только с разрешения клиента.</p></article><article><span>Екатеринбург</span><h3>Уборка квартиры<br>после ремонта</h3><p>Площадь, срок и результат — честно и по делу.</p></article></div></section>
<section class="section districts"><p class="eyebrow">География выезда</p><h2>Во все районы<br><em>Екатеринбурга.</em></h2><p>Уралмаш · Эльмаш · Центр · Академический · ВИЗ · ЖБИ · Ботаника · Вторчермет · Пионерский · Юго-Западный · Сортировка · Широкая речка</p></section>
<section class="section faq" id="faq"><div><p class="eyebrow">FAQ</p><h2>Отвечаем до того,<br><em>как вы спросите.</em></h2></div><div>${faq.map((item)=>`<details><summary>${safe(item.q)}<span>+</span></summary><p>${safe(item.a)}</p></details>`).join("")}</div></section>`, {page:"Клининг и химчистка",description:"Клининг квартир, уборка после ремонта, химчистка диванов и ковров в Екатеринбурге. Расчёт стоимости и удобная запись.",canonical:"",schema:[localBusinessSchema,faqSchema]});
const servicePage = (s) => layout(`<section class="inner-hero"><p class="eyebrow">Услуги · Екатеринбург</p><h1>${safe(s.name)}<br><em>с выездом.</em></h1><p>${safe(s.description)}</p><div class="inner-price">от ${money(s.price)} ₽ <small>· ${safe(s.duration)}</small></div><a class="button" href="/#booking">Записаться <span>→</span></a></section><section class="section service-detail"><div><p class="eyebrow">Что входит</p><h2>Честный объём<br><em>работ.</em></h2></div><ul>${s.includes.map((i)=>`<li>✦ ${safe(i)}</li>`).join("")}</ul></section><section class="section notice"><p>Финальная стоимость зависит от площади, материалов, загрязнения и количества предметов. Пришлите фото — заранее сориентируем точнее.</p><a class="button" href="/#photo">Отправить фото</a></section><section class="section related"><p class="eyebrow">Другие задачи</p><div class="service-grid">${data.services.filter((item)=>item.slug!==s.slug).slice(0,3).map(serviceCard).join("")}</div></section>`, {page:s.name,description:`${s.name} в Екатеринбурге — ${s.short}. Цена от ${money(s.price)} ₽.`,canonical:`${s.slug}.html`,schema:[serviceSchema(s)]});
const privacy = () => layout(`<section class="legal"><p class="eyebrow">Документ</p><h1>Политика обработки<br><em>персональных данных.</em></h1><p class="updated">Версия для заполнения перед публикацией · 20 сентября 2026 г.</p><h2>1. Оператор</h2><p>Оператором является самозанятая [ФИО], ИНН [ИНН], адрес для обращений: [адрес / email]. До публикации обязательно замените реквизиты в квадратных скобках.</p><h2>2. Какие данные и зачем</h2><p>Имя, телефон, адрес, комментарий, выбранная услуга, дата и время нужны только для обратной связи, расчёта и выполнения заявки. Основание — согласие субъекта персональных данных.</p><h2>3. Хранение и защита</h2><p>Персональные данные хранятся в защищённом российском контуре не дольше 6 месяцев с даты заявки, если более долгий срок не требует закон. Технические логи минимизируются. Имя, телефон, адрес и заметки не хранятся в Cloudflare и не передаются в аналитику.</p><h2>4. Передача и удаление</h2><p>Данные могут использоваться для связи с клиентом через согласованные мессенджеры. Для отзыва согласия, удаления или уточнения данных напишите на [email]. Обращение будет рассмотрено в срок, установленный законом.</p><h2>5. Аналитика</h2><p>Если подключается Яндекс.Метрика, поля имени и телефона исключаются из записи сессии. Не отправляйте персональные данные в поля поиска и формы аналитики.</p></section>`, {page:"Политика обработки персональных данных",description:"Политика обработки персональных данных сервиса клининга.",canonical:"privacy.html"});

await rm(out, {recursive:true, force:true}); await mkdir(out, {recursive:true});
await mkdir(new URL("assets/", out), {recursive:true});
for (const asset of ["site.css", "site.js", "config.js", "hero-interior.webp"]) {
  await cp(new URL(`assets/${asset}`, root), new URL(`assets/${asset}`, out));
}
await writeFile(new URL("index.html",out), home());
await writeFile(new URL("privacy.html",out), privacy());
for (const s of data.services) await writeFile(new URL(`${s.slug}.html`,out), servicePage(s));
const urls = ["", "privacy.html", ...data.services.map((s)=>`${s.slug}.html`)];
await writeFile(new URL("robots.txt",out), "User-agent: *\nAllow: /\nSitemap: https://example.ru/sitemap.xml\n");
await writeFile(new URL("sitemap.xml",out), `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map((u)=>`<url><loc>https://example.ru/${u}</loc></url>`).join("")}</urlset>`);
await writeFile(new URL("site.webmanifest",out), JSON.stringify({name:data.brand,short_name:data.brand,start_url:"/",display:"standalone",background_color:"#f6f5ef",theme_color:"#0b7774",icons:[]}));
await writeFile(new URL("favicon.svg",out), '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="18" fill="#0b7774"/><path d="M32 12l4.8 14.8L52 32l-15.2 5.2L32 52l-5.2-14.8L12 32l14.8-5.2z" fill="#d7ef76"/></svg>');
console.log(`Built ${urls.length} pages from data/services.json`);
